# Generated by Django 4.2.9 on 2024-03-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Может пользователь авторизовываться'),
        ),
    ]
