# Generated by Django 4.2.9 on 2024-03-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-is_active', '-email']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
