# Generated by Django 4.2.9 on 2024-01-14 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='end_datatime_mailing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='messagemailing',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(max_length=150, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('1', 'раз в день'), ('7', 'раз в неделю'), ('30', 'раз в месяц')], default='1', verbose_name='Периодичность: раз в день, раз в неделю, раз в месяц'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Завершена', 'Завершена'), ('Создана', 'Создана'), ('Запущена', 'Запущена')], default='Создана', max_length=100, verbose_name='Статус рассылки'),
        ),
    ]
