# Generated by Django 4.2.9 on 2024-01-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_end_datatime_mailing_messagemailing_mailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='сlient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
