# Generated by Django 4.2.9 on 2024-01-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_end_datatime_mailing_messagemailing_mailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='сlient',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Пользователь'),
        ),
    ]
