# Generated by Django 4.2.9 on 2024-01-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_client_comment_alter_client_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='сlient',
            new_name='сlient_key',
        ),
    ]
