# Generated by Django 4.2.9 on 2024-01-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_rename_сlient_mailing_сlient_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='сlient_key',
        ),
        migrations.AddField(
            model_name='mailing',
            name='сlient_key',
            field=models.ManyToManyField(blank=True, null=True, to='mailing.client', verbose_name='Пользователь'),
        ),
    ]
