# Generated by Django 4.2.9 on 2024-01-19 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_remove_mailing_сlient_key_mailing_сlient_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsmailing',
            name='mailing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', unique=True, verbose_name='Рассылка'),
            preserve_default=False,
        ),
    ]
