# Generated by Django 4.2.9 on 2024-01-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_logsmailing_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsmailing',
            name='mailing',
        ),
    ]
