# Generated by Django 4.2.9 on 2024-01-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_remove_logsmailing_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='сlient_key',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Пользователь'),
        ),
    ]
