# Generated by Django 5.0.1 on 2024-01-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_mailing_owner_alter_mailing_end_datatime_mailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsmailing',
            name='mailing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
            preserve_default=False,
        ),
    ]
