# Generated by Django 5.0.1 on 2024-02-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_logsmailing_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-status', 'end_datatime_mailing'], 'permissions': [('set_status', 'Can publish mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
