# Generated by Django 5.0.1 on 2024-02-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['date_create'], 'permissions': [('set_is_published', 'Может публиковать товары')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
    ]
